# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Russ Childers"
description: > # this means to ignore newlines until "baseurl:"
  Russ Childers is available for programs on Appalachian traditions, from one-hour
  presentations to two or three-week residencies which may include storytelling,
  music and songs with traditional instruments, or basic techniques in
  mountain-style squaredancing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://russchilders.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Reading Files
include:
  - _pages

# Site Author
author:
  name             : "Russ Childers"
  avatar           : "bio-photo.jpg"
  bio              :
  address          : "1555 Old State Route 74"
  citystatezip     : "Batavia, Ohio 45103"
  phone            : "513-732-2015"
  email            : "russchilders1@gmail.com"
  facebook         : BearFootMusicStoriesDance

barb_email: "barbchilders1@gmail.com"

#gems:
#  - jekyll-paginate
#    jekyll-gallery-generator

gallery:
  # path to the gallery
  dir: gallery
  # title for gallery index
  title: "Gallery"

paginate: 5 # amount of posts to show
paginate_path: /posts/page:num/
timezone: America/New_York # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
